import { Service } from './store';

export const serviceCategories = [
  { id: 'pensions', icon: '🏦', nameKey: 'pensions' },
  { id: 'social-welfare', icon: '🤝', nameKey: 'socialWelfare' },
  { id: 'health', icon: '🏥', nameKey: 'health' },
  { id: 'education', icon: '🎓', nameKey: 'education' },
  { id: 'agriculture', icon: '🌾', nameKey: 'agriculture' },
  { id: 'transport', icon: '🚗', nameKey: 'transport' },
  { id: 'utilities', icon: '💡', nameKey: 'utilities' },
  { id: 'tax-finance', icon: '💰', nameKey: 'taxFinance' },
];

export const states = [
  { id: 'central', name: 'Central Government' },
  { id: 'maharashtra', name: 'Maharashtra' },
  { id: 'gujarat', name: 'Gujarat' },
  { id: 'karnataka', name: 'Karnataka' },
  { id: 'delhi', name: 'Delhi' },
  { id: 'tamilnadu', name: 'Tamil Nadu' },
  { id: 'kerala', name: 'Kerala' },
  { id: 'westbengal', name: 'West Bengal' },
  { id: 'rajasthan', name: 'Rajasthan' },
  { id: 'punjab', name: 'Punjab' },
  { id: 'telangana', name: 'Telangana' },
  { id: 'andhrapradesh', name: 'Andhra Pradesh' },
  { id: 'uttarpradesh', name: 'Uttar Pradesh' },
];

export const services: Service[] = [
  // Pensions & EPFO
  {
    id: 'epf-balance',
    name: 'Check EPF Balance',
    description: 'View your Employee Provident Fund balance and recent contributions',
    category: 'pensions',
    eligibility: 'Any EPF member with UAN',
    documents: ['UAN Number', 'Aadhaar Card'],
    state: 'central',
  },
  {
    id: 'epf-claim',
    name: 'EPF Withdrawal Claim',
    description: 'Submit a claim for EPF withdrawal',
    category: 'pensions',
    eligibility: 'EPF members who have left employment',
    documents: ['UAN Number', 'Bank Account Details', 'Aadhaar Card', 'PAN Card'],
    state: 'central',
  },
  {
    id: 'pension-status',
    name: 'Pension Status Check',
    description: 'Check the status of your pension application',
    category: 'pensions',
    eligibility: 'Retired employees who have applied for pension',
    documents: ['PPO Number', 'Aadhaar Card'],
    state: 'central',
  },
  {
    id: 'atal-pension',
    name: 'Atal Pension Yojana',
    description: 'Guaranteed pension scheme for unorganized sector workers',
    category: 'pensions',
    eligibility: 'Indian citizens aged 18-40 with bank account',
    documents: ['Aadhaar Card', 'Bank Account Details', 'Mobile Number'],
    state: 'central',
  },
  {
    id: 'old-age-pension',
    name: 'Old Age Pension Scheme',
    description: 'Monthly pension for senior citizens above 60 years',
    category: 'pensions',
    eligibility: 'Citizens above 60 years with income below poverty line',
    documents: ['Aadhaar Card', 'Age Proof', 'Income Certificate', 'Bank Account'],
    state: 'central',
  },
  {
    id: 'varishtha-pension',
    name: 'Varishtha Pension Bima Yojana',
    description: 'Pension scheme for senior citizens with assured returns',
    category: 'pensions',
    eligibility: 'Senior citizens above 60 years',
    documents: ['Aadhaar Card', 'Age Proof', 'PAN Card', 'Bank Account'],
    state: 'central',
  },
  
  // Social Welfare
  {
    id: 'pm-kisan',
    name: 'PM Kisan Samman Nidhi',
    description: 'Get ₹6000 per year direct benefit transfer for farmers',
    category: 'social-welfare',
    eligibility: 'Small and marginal farmers with cultivable land',
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account Details'],
    state: 'central',
  },
  {
    id: 'ration-card',
    name: 'Ration Card Application',
    description: 'Apply for new ration card or update existing one',
    category: 'social-welfare',
    eligibility: 'All Indian citizens',
    documents: ['Aadhaar Card', 'Address Proof', 'Income Certificate'],
    state: 'maharashtra',
  },
  {
    id: 'widow-pension',
    name: 'Widow Pension Scheme',
    description: 'Monthly pension for widows below poverty line',
    category: 'social-welfare',
    eligibility: 'Widows aged 18-60 with income below ₹1 lakh',
    documents: ['Aadhaar Card', 'Death Certificate of Spouse', 'Income Certificate'],
    state: 'gujarat',
  },
  {
    id: 'ujjwala',
    name: 'PM Ujjwala Yojana',
    description: 'Free LPG connection for women from BPL households',
    category: 'social-welfare',
    eligibility: 'Women from BPL households without LPG connection',
    documents: ['BPL Card', 'Aadhaar Card', 'Bank Account', 'Passport Photo'],
    state: 'central',
  },
  {
    id: 'awas-yojana',
    name: 'PM Awas Yojana',
    description: 'Affordable housing scheme for economically weaker sections',
    category: 'social-welfare',
    eligibility: 'EWS/LIG families without pucca house',
    documents: ['Aadhaar Card', 'Income Certificate', 'Land Documents', 'Bank Account'],
    state: 'central',
  },
  {
    id: 'sukanya-samriddhi',
    name: 'Sukanya Samriddhi Yojana',
    description: 'Savings scheme for girl child education and marriage',
    category: 'social-welfare',
    eligibility: 'Parents/guardians of girl child below 10 years',
    documents: ['Birth Certificate', 'Aadhaar of Guardian', 'Address Proof'],
    state: 'central',
  },
  {
    id: 'disability-pension',
    name: 'Disability Pension Scheme',
    description: 'Monthly pension for persons with disabilities',
    category: 'social-welfare',
    eligibility: 'Persons with 40% or more disability',
    documents: ['Disability Certificate', 'Aadhaar Card', 'Income Certificate'],
    state: 'central',
  },
  {
    id: 'antyodaya-anna',
    name: 'Antyodaya Anna Yojana',
    description: 'Subsidized food grains for poorest of poor families',
    category: 'social-welfare',
    eligibility: 'Poorest families identified by state government',
    documents: ['BPL Card', 'Aadhaar Card', 'Income Certificate'],
    state: 'central',
  },
  {
    id: 'kalyana-lakshmi',
    name: 'Kalyana Lakshmi Scheme',
    description: 'Financial assistance for marriage of girls from poor families',
    category: 'social-welfare',
    eligibility: 'SC/ST/BC/Minority girls above 18 years',
    documents: ['Caste Certificate', 'Aadhaar Card', 'Age Proof', 'Bank Account'],
    state: 'telangana',
  },
  {
    id: 'kanyashree',
    name: 'Kanyashree Prakalpa',
    description: 'Scholarship and conditional cash transfer for girls',
    category: 'social-welfare',
    eligibility: 'Girls aged 13-18 from families with income below ₹1.2 lakh',
    documents: ['Age Proof', 'Income Certificate', 'School Certificate', 'Bank Account'],
    state: 'westbengal',
  },
  
  // Health
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat PM-JAY',
    description: 'Get health insurance coverage up to ₹5 lakh per family',
    category: 'health',
    eligibility: 'Families identified in SECC database',
    documents: ['Aadhaar Card', 'Ration Card'],
    state: 'central',
  },
  {
    id: 'vaccination',
    name: 'COVID Vaccination Certificate',
    description: 'Download your COVID-19 vaccination certificate',
    category: 'health',
    eligibility: 'Anyone who has received COVID vaccination',
    documents: ['Mobile Number registered during vaccination'],
    state: 'central',
  },
  {
    id: 'janani-suraksha',
    name: 'Janani Suraksha Yojana',
    description: 'Cash assistance for institutional delivery',
    category: 'health',
    eligibility: 'Pregnant women from BPL families',
    documents: ['Aadhaar Card', 'BPL Card', 'MCH Card', 'Bank Account'],
    state: 'central',
  },
  {
    id: 'health-card',
    name: 'Ayushman Bharat Health Card',
    description: 'Apply for Ayushman Bharat Health Account card',
    category: 'health',
    eligibility: 'All Indian citizens',
    documents: ['Aadhaar Card', 'Mobile Number', 'Passport Photo'],
    state: 'central',
  },
  {
    id: 'tb-treatment',
    name: 'Nikshay Poshan Yojana',
    description: 'Nutritional support for TB patients',
    category: 'health',
    eligibility: 'All TB patients undergoing treatment',
    documents: ['TB Treatment Card', 'Aadhaar Card', 'Bank Account'],
    state: 'central',
  },
  {
    id: 'arogyasri',
    name: 'YSR Aarogyasri Scheme',
    description: 'Free medical treatment for BPL families',
    category: 'health',
    eligibility: 'BPL families of Andhra Pradesh',
    documents: ['White Ration Card', 'Aadhaar Card'],
    state: 'andhrapradesh',
  },
  {
    id: 'chiranjeevi',
    name: 'Chiranjeevi Health Insurance',
    description: 'Health insurance up to ₹25 lakh for families',
    category: 'health',
    eligibility: 'All families of Rajasthan',
    documents: ['Jan Aadhaar Card', 'Aadhaar Card'],
    state: 'rajasthan',
  },
  {
    id: 'ma-amrutham',
    name: 'Mahatma Jyotiba Phule Jan Arogya',
    description: 'Health insurance for BPL families in Maharashtra',
    category: 'health',
    eligibility: 'BPL families with annual income below ₹1.5 lakh',
    documents: ['Yellow/Orange Ration Card', 'Aadhaar Card'],
    state: 'maharashtra',
  },
  
  // Education
  {
    id: 'scholarship',
    name: 'National Scholarship Portal',
    description: 'Apply for various central and state scholarships',
    category: 'education',
    eligibility: 'Students meeting income and academic criteria',
    documents: ['Aadhaar Card', 'Income Certificate', 'Marksheet', 'Bank Account'],
    state: 'central',
  },
  {
    id: 'vidyasiri',
    name: 'Vidyasiri Scholarship',
    description: 'Scholarship for SC/ST students in Karnataka',
    category: 'education',
    eligibility: 'SC/ST students of Karnataka with income below ₹2.5 lakh',
    documents: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'College ID'],
    state: 'karnataka',
  },
  {
    id: 'post-matric',
    name: 'Post Matric Scholarship',
    description: 'Scholarship for SC/ST/OBC students for higher education',
    category: 'education',
    eligibility: 'SC/ST/OBC students with family income below limit',
    documents: ['Caste Certificate', 'Income Certificate', 'Marksheet', 'Admission Letter'],
    state: 'central',
  },
  {
    id: 'minority-scholarship',
    name: 'Pre/Post Matric Scholarship for Minorities',
    description: 'Scholarship for students from minority communities',
    category: 'education',
    eligibility: 'Students from minority communities with income below ₹2 lakh',
    documents: ['Minority Certificate', 'Income Certificate', 'Marksheet', 'Bank Account'],
    state: 'central',
  },
  {
    id: 'mudra-loan',
    name: 'PM MUDRA Yojana',
    description: 'Loans up to ₹10 lakh for small business and education',
    category: 'education',
    eligibility: 'Non-corporate small business and students',
    documents: ['Aadhaar Card', 'Business Plan', 'Bank Statements', 'Address Proof'],
    state: 'central',
  },
  {
    id: 'vidyalakshmi',
    name: 'Vidya Lakshmi Education Loan',
    description: 'Education loan portal for higher studies',
    category: 'education',
    eligibility: 'Students admitted to recognized institutions',
    documents: ['Admission Letter', 'Marksheets', 'Income Proof', 'Collateral Documents'],
    state: 'central',
  },
  {
    id: 'oasis-scholarship',
    name: 'OASIS Scholarship',
    description: 'Online application for scholarships in West Bengal',
    category: 'education',
    eligibility: 'Students of West Bengal with family income criteria',
    documents: ['Aadhaar Card', 'Income Certificate', 'Marksheet', 'Bank Account'],
    state: 'westbengal',
  },
  {
    id: 'medhavi-chhatra',
    name: 'Medhavi Chhatra Yojana',
    description: 'Scholarship for meritorious students in MP',
    category: 'education',
    eligibility: 'Students scoring above 70% in Class 12',
    documents: ['Marksheet', 'Aadhaar Card', 'Income Certificate', 'College Admission'],
    state: 'central',
  },
  
  // Agriculture
  {
    id: 'soil-health',
    name: 'Soil Health Card',
    description: 'Get your soil tested and receive recommendations',
    category: 'agriculture',
    eligibility: 'All farmers',
    documents: ['Aadhaar Card', 'Land Records'],
    state: 'central',
  },
  {
    id: 'crop-insurance',
    name: 'PM Fasal Bima Yojana',
    description: 'Crop insurance scheme for farmers',
    category: 'agriculture',
    eligibility: 'Farmers growing notified crops',
    documents: ['Aadhaar Card', 'Land Records', 'Sowing Certificate', 'Bank Account'],
    state: 'central',
  },
  {
    id: 'kisan-credit',
    name: 'Kisan Credit Card',
    description: 'Credit facility for farmers at subsidized interest',
    category: 'agriculture',
    eligibility: 'All farmers including tenant farmers',
    documents: ['Aadhaar Card', 'Land Records', 'Identity Proof', 'Passport Photo'],
    state: 'central',
  },
  {
    id: 'pm-kusum',
    name: 'PM KUSUM Yojana',
    description: 'Solar pumps and grid-connected solar plants for farmers',
    category: 'agriculture',
    eligibility: 'Farmers with agricultural land',
    documents: ['Land Records', 'Aadhaar Card', 'Bank Account', 'Electricity Bill'],
    state: 'central',
  },
  {
    id: 'e-nam',
    name: 'e-NAM (National Agriculture Market)',
    description: 'Online trading platform for agricultural commodities',
    category: 'agriculture',
    eligibility: 'Farmers, traders, and commission agents',
    documents: ['Aadhaar Card', 'Bank Account', 'Mobile Number'],
    state: 'central',
  },
  {
    id: 'rythu-bandhu',
    name: 'Rythu Bandhu Scheme',
    description: '₹10,000 per acre investment support for farmers',
    category: 'agriculture',
    eligibility: 'All farmers of Telangana with land ownership',
    documents: ['Land Records (Pahani)', 'Aadhaar Card', 'Bank Account'],
    state: 'telangana',
  },
  {
    id: 'ysr-rythu',
    name: 'YSR Rythu Bharosa',
    description: 'Investment support for farmers in Andhra Pradesh',
    category: 'agriculture',
    eligibility: 'Farmers with cultivable land in AP',
    documents: ['Land Records', 'Aadhaar Card', 'Bank Account'],
    state: 'andhrapradesh',
  },
  {
    id: 'kalia-scheme',
    name: 'KALIA Scheme',
    description: 'Financial assistance for farmers in Odisha',
    category: 'agriculture',
    eligibility: 'Small and marginal farmers of Odisha',
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account'],
    state: 'central',
  },
  
  // Transport
  {
    id: 'driving-license',
    name: 'Driving License Application',
    description: 'Apply for new driving license or renewal',
    category: 'transport',
    eligibility: 'Indian citizens above 18 years',
    documents: ['Aadhaar Card', 'Address Proof', 'Passport Photo', 'Medical Certificate'],
    state: 'central',
  },
  {
    id: 'vehicle-registration',
    name: 'Vehicle Registration (RC)',
    description: 'Register new vehicle or transfer ownership',
    category: 'transport',
    eligibility: 'Vehicle owners',
    documents: ['Invoice', 'Insurance', 'Aadhaar Card', 'Address Proof'],
    state: 'delhi',
  },
  {
    id: 'international-dl',
    name: 'International Driving Permit',
    description: 'Apply for International Driving Permit',
    category: 'transport',
    eligibility: 'Valid Indian DL holders travelling abroad',
    documents: ['Valid DL', 'Passport', 'Passport Photos', 'Travel Documents'],
    state: 'central',
  },
  {
    id: 'learner-license',
    name: 'Learner License Application',
    description: 'Apply for learner driving license',
    category: 'transport',
    eligibility: 'Indian citizens above 16 years (for motorcycle without gear)',
    documents: ['Aadhaar Card', 'Age Proof', 'Passport Photo', 'Address Proof'],
    state: 'central',
  },
  {
    id: 'vehicle-fitness',
    name: 'Vehicle Fitness Certificate',
    description: 'Renew fitness certificate for commercial vehicles',
    category: 'transport',
    eligibility: 'Commercial vehicle owners',
    documents: ['RC Book', 'Insurance', 'Pollution Certificate', 'Tax Receipt'],
    state: 'central',
  },
  {
    id: 'fastag',
    name: 'FASTag Application',
    description: 'Apply for FASTag for electronic toll collection',
    category: 'transport',
    eligibility: 'All vehicle owners',
    documents: ['RC Book', 'Aadhaar Card', 'Passport Photo'],
    state: 'central',
  },
  {
    id: 'e-challan',
    name: 'E-Challan Payment',
    description: 'Pay traffic violation challans online',
    category: 'transport',
    eligibility: 'Anyone with pending traffic challan',
    documents: ['Challan Number', 'Vehicle Number'],
    state: 'central',
  },
  
  // Utilities
  {
    id: 'electricity-bill',
    name: 'Pay Electricity Bill',
    description: 'Pay your electricity bill online',
    category: 'utilities',
    eligibility: 'All electricity consumers',
    documents: ['Consumer Number', 'Bill Copy'],
    state: 'central',
  },
  {
    id: 'gas-booking',
    name: 'LPG Gas Booking',
    description: 'Book LPG cylinder refill online',
    category: 'utilities',
    eligibility: 'LPG connection holders',
    documents: ['Consumer Number', 'Registered Mobile'],
    state: 'central',
  },
  {
    id: 'water-bill',
    name: 'Pay Water Bill',
    description: 'Pay your municipal water bill',
    category: 'utilities',
    eligibility: 'All water connection holders',
    documents: ['Consumer Number'],
    state: 'maharashtra',
  },
  {
    id: 'new-electricity',
    name: 'New Electricity Connection',
    description: 'Apply for new electricity connection',
    category: 'utilities',
    eligibility: 'Property owners without electricity connection',
    documents: ['Property Documents', 'Aadhaar Card', 'NOC from Society', 'Passport Photo'],
    state: 'central',
  },
  {
    id: 'new-water',
    name: 'New Water Connection',
    description: 'Apply for new municipal water connection',
    category: 'utilities',
    eligibility: 'Property owners without water connection',
    documents: ['Property Documents', 'Aadhaar Card', 'Building Plan Approval'],
    state: 'central',
  },
  {
    id: 'gas-subsidy',
    name: 'LPG Subsidy Status',
    description: 'Check LPG subsidy credit status',
    category: 'utilities',
    eligibility: 'LPG consumers enrolled in DBTL',
    documents: ['LPG Consumer Number', 'Aadhaar Number'],
    state: 'central',
  },
  {
    id: 'piped-gas',
    name: 'PNG Connection Application',
    description: 'Apply for Piped Natural Gas connection',
    category: 'utilities',
    eligibility: 'Residents in PNG service areas',
    documents: ['Property Documents', 'Aadhaar Card', 'NOC', 'Passport Photo'],
    state: 'central',
  },
  
  // Tax & Finance
  {
    id: 'income-tax',
    name: 'File Income Tax Return',
    description: 'File your annual income tax return online',
    category: 'tax-finance',
    eligibility: 'All taxpayers',
    documents: ['PAN Card', 'Aadhaar Card', 'Form 16', 'Bank Statements'],
    state: 'central',
  },
  {
    id: 'jan-dhan',
    name: 'Jan Dhan Account',
    description: 'Open zero-balance bank account under PMJDY',
    category: 'tax-finance',
    eligibility: 'Indian citizens without bank account',
    documents: ['Aadhaar Card', 'Passport Photo'],
    state: 'central',
  },
  {
    id: 'nps',
    name: 'National Pension System',
    description: 'Open NPS account for retirement savings',
    category: 'tax-finance',
    eligibility: 'Indian citizens aged 18-65',
    documents: ['Aadhaar Card', 'PAN Card', 'Bank Account Details'],
    state: 'central',
  },
  {
    id: 'pan-card',
    name: 'PAN Card Application',
    description: 'Apply for new PAN card or correction',
    category: 'tax-finance',
    eligibility: 'All Indian citizens and entities',
    documents: ['Aadhaar Card', 'Passport Photo', 'Address Proof'],
    state: 'central',
  },
  {
    id: 'gst-registration',
    name: 'GST Registration',
    description: 'Register for Goods and Services Tax',
    category: 'tax-finance',
    eligibility: 'Businesses with turnover above threshold',
    documents: ['PAN Card', 'Aadhaar Card', 'Business Proof', 'Bank Account', 'Photos'],
    state: 'central',
  },
  {
    id: 'pm-svanidhi',
    name: 'PM SVANidhi Scheme',
    description: 'Micro loans for street vendors',
    category: 'tax-finance',
    eligibility: 'Street vendors with certificate of vending',
    documents: ['Vending Certificate', 'Aadhaar Card', 'Bank Account', 'Passport Photo'],
    state: 'central',
  },
  {
    id: 'stand-up-india',
    name: 'Stand Up India Loan',
    description: 'Loans for SC/ST and women entrepreneurs',
    category: 'tax-finance',
    eligibility: 'SC/ST/Women entrepreneurs above 18 years',
    documents: ['Caste Certificate', 'Business Plan', 'Aadhaar Card', 'Bank Statements'],
    state: 'central',
  },
  {
    id: 'ppf',
    name: 'Public Provident Fund Account',
    description: 'Long-term savings with tax benefits',
    category: 'tax-finance',
    eligibility: 'All Indian citizens',
    documents: ['Aadhaar Card', 'PAN Card', 'Passport Photo', 'Address Proof'],
    state: 'central',
  },
  {
    id: 'tax-refund',
    name: 'Income Tax Refund Status',
    description: 'Check status of your income tax refund',
    category: 'tax-finance',
    eligibility: 'Taxpayers who have filed returns',
    documents: ['PAN Card', 'Acknowledgment Number'],
    state: 'central',
  },
  {
    id: 'property-tax',
    name: 'Pay Property Tax',
    description: 'Pay your municipal property tax online',
    category: 'tax-finance',
    eligibility: 'All property owners',
    documents: ['Property ID', 'Previous Receipt'],
    state: 'central',
  },
];

export const getServicesByCategory = (categoryId: string): Service[] => {
  return services.filter((s) => s.category === categoryId);
};

export const getServiceById = (id: string): Service | undefined => {
  return services.find((s) => s.id === id);
};

export const searchServices = (query: string): Service[] => {
  const lowerQuery = query.toLowerCase();
  return services.filter(
    (s) =>
      s.name.toLowerCase().includes(lowerQuery) ||
      s.description.toLowerCase().includes(lowerQuery) ||
      s.category.toLowerCase().includes(lowerQuery)
  );
};

export const filterServices = (filters: {
  category?: string;
  state?: string;
}): Service[] => {
  return services.filter((s) => {
    if (filters.category && s.category !== filters.category) return false;
    if (filters.state && s.state !== filters.state && s.state !== 'central') return false;
    return true;
  });
};
